# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cin_extraction_pb2 as cin__extraction__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cin_extraction_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CinExtractionServiceStub(object):
    """The CIN extraction service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExtractCinData = channel.unary_unary(
                '/cinextraction.CinExtractionService/ExtractCinData',
                request_serializer=cin__extraction__pb2.CinRequest.SerializeToString,
                response_deserializer=cin__extraction__pb2.CinResponse.FromString,
                _registered_method=True)


class CinExtractionServiceServicer(object):
    """The CIN extraction service definition
    """

    def ExtractCinData(self, request, context):
        """Send a CIN image and receive extraction results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CinExtractionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExtractCinData': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractCinData,
                    request_deserializer=cin__extraction__pb2.CinRequest.FromString,
                    response_serializer=cin__extraction__pb2.CinResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cinextraction.CinExtractionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cinextraction.CinExtractionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CinExtractionService(object):
    """The CIN extraction service definition
    """

    @staticmethod
    def ExtractCinData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cinextraction.CinExtractionService/ExtractCinData',
            cin__extraction__pb2.CinRequest.SerializeToString,
            cin__extraction__pb2.CinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
