# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cin_extraction.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'cin_extraction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63in_extraction.proto\x12\rcinextraction\"2\n\nCinRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"\xb5\x01\n\x0b\x43inResponse\x12\x11\n\tid_number\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08lastname\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\x12\x0f\n\x07success\x18\x05 \x01(\x08\x12\x15\n\rconfidence_id\x18\x06 \x01(\x02\x12\x17\n\x0f\x63onfidence_name\x18\x07 \x01(\x02\x12\x1b\n\x13\x63onfidence_lastname\x18\x08 \x01(\x02\x32\x61\n\x14\x43inExtractionService\x12I\n\x0e\x45xtractCinData\x12\x19.cinextraction.CinRequest\x1a\x1a.cinextraction.CinResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cin_extraction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CINREQUEST']._serialized_start=39
  _globals['_CINREQUEST']._serialized_end=89
  _globals['_CINRESPONSE']._serialized_start=92
  _globals['_CINRESPONSE']._serialized_end=273
  _globals['_CINEXTRACTIONSERVICE']._serialized_start=275
  _globals['_CINEXTRACTIONSERVICE']._serialized_end=372
# @@protoc_insertion_point(module_scope)
