# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import plate_detection_pb2 as plate__detection__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in plate_detection_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlateDetectionServiceStub(object):
    """The plate detection service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectPlate = channel.unary_unary(
                '/platedetection.PlateDetectionService/DetectPlate',
                request_serializer=plate__detection__pb2.PlateRequest.SerializeToString,
                response_deserializer=plate__detection__pb2.PlateResponse.FromString,
                _registered_method=True)


class PlateDetectionServiceServicer(object):
    """The plate detection service definition
    """

    def DetectPlate(self, request, context):
        """Send a car image and receive plate detection results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlateDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectPlate': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectPlate,
                    request_deserializer=plate__detection__pb2.PlateRequest.FromString,
                    response_serializer=plate__detection__pb2.PlateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'platedetection.PlateDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('platedetection.PlateDetectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlateDetectionService(object):
    """The plate detection service definition
    """

    @staticmethod
    def DetectPlate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/platedetection.PlateDetectionService/DetectPlate',
            plate__detection__pb2.PlateRequest.SerializeToString,
            plate__detection__pb2.PlateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
